version: '3.9'

services:

    node:
        image: node:latest
        ports:
            # - "80:80"
            - "3000:3000"
            - "443:443"
            - "35729:35729" #for hotreloading
        volumes: 
            - ./webpack-from-scratch:/usr/src/app
        #   - .:/usr/src/app
        working_dir: /usr/src/app
        stdin_open: true
        tty: true
        environment: 
            - CHOKIDAR_USEPOLLING=true #requried for docker and VM
            # - DEBUG=express
            # - NODE_ENV=dev
        command: tail -f /dev/null #container will not stop on begging
        # command: yarn start #bash